### ISSUE TITLE
Publishing this!

### ISSUE THREAD

**Issue by purcell** [nix-community/nix-ts-mode#1]
Hi! I found this while considering writing my own `nix-ts-mode` and it looks like you've made good progress. Can I help you get it into MELPA? The only immediate blocker I can see is that you'd need to specify a GPL-compatible licence — I'd suggest going with straight GPLv3 so that it could theoretically even be included in Emacs in future.

**Comment by purcell** [comment]
You should also remove (or move into a subdirectory) `utils.el` so it doesn't look like it is meant to be part of the package contents.

**Comment by remi-gelinas** [comment]
Thanks for #2, I haven't prepped a MELPA package before, so I definitely left stuff out.

As for licensing, I'm happy to license this as GPLv3 - I think there were a few concerns around referencing neovim's Nix treesitter queries. Considering neovim does not have a compatible license, if I recall.

That said, the queries are not directly taken in most cases, and the starter guide for treesit queries [here ](https://github.com/emacs-mirror/emacs/blob/master/admin/notes/tree-sitter/starter-guide)mentions using neovim's queries as references for new ts modes, so I'm not sure if it really matters.

**Comment by purcell** [comment]
> Thanks for #2, I haven't prepped a MELPA package before, so I definitely left stuff out.

It was actually in very good shape tbh. :)

> As for licensing, I'm happy to license this as GPLv3 - I think there were a few concerns around referencing neovim's Nix treesitter queries. Considering neovim does not have a compatible license, if I recall.

Neovim appears to be Apache 2.0, which is [GPL compatible](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses).

> That said, the queries are not directly taken in most cases, and the starter guide for treesit queries [here ](https://github.com/emacs-mirror/emacs/blob/master/admin/notes/tree-sitter/starter-guide)mentions using neovim's queries as references for new ts modes, so I'm not sure if it really matters.

Yes, I would think that for a query or two it's not an issue.

**Comment by remi-gelinas** [comment]
@purcell Looks like you're good to go to add a recipe then! :D

**Comment by purcell** [comment]
Done, will just take a few hours or less before it builds for the first time.

**Comment by purcell** [comment]
It's [there now](https://melpa.org/#/nix-ts-mode) — you might like to stick a badge in the README. 😄

**Comment by purcell** [comment]
I may have mentioned this on Mastodon, so the fresh stars could be partly my fault. Nice job with the README, and let me know if I can help with anything.

**Comment by purcell** [comment]
Also if you add a version tag, e.g. `0.1` or `v0.1` then MELPA Stable will automatically build a release version.
