### ISSUE TITLE
Transfer this repo to nix-community?

### ISSUE THREAD

**Issue by antifuchs** [nix-community/nix-ts-mode#19]
This was suggested on the https://matrix.to/#/#emacs:nixos.org channel, and it makes a good amount of sense: A few contributors exist who would love to land fixes and maintenance patches, and over in nix-community (or any other active organization really), it has a chance to let the swarm keep working on it.

**Comment by purcell** [comment]
I would support that, personally!

**Comment by remi-gelinas** [comment]
I'm all for it - unfortunately I don't have nearly as much time as I wanted to properly maintain this.

Are there are docs on the process for transferring it?

**Comment by antifuchs** [comment]
I did some looking recently, and the process is just about this:

1. you suggest transferring this repo to the org in https://github.com/orgs/nix-community/discussions
2. They invite you and create a team for you
3. You transfer the repo in
4. They give you the repo back and you get invite permissions

After that, it’s only a matter of spreading the commit bits around (:

**Comment by Atemu** [comment]
This can be closed.

**Comment by antifuchs** [comment]
Ah, I forgot to ask for the second step there: @remi-gelinas, would you mind adding other maintainers so some long-standing PRs can get merged? I would be happy to take on some PR-reviewing/merging duties, and maybe @purcell would like to do so also?

**Comment by purcell** [comment]
I think Remi is still waiting to be given elevated permissions to the repo, and may not yet be able to adjust the team yet.

**Comment by remi-gelinas** [comment]
Awesome - as of now, I've been given full permissions to the repository. Just catching up on some changes to the release process, codeowners, etc. now that there is a team maintaining. @antifuchs I'll add you to the team, @purcell is already a maintainer I believe - I'll double check though. As transfer is complete, I'll close this out :D

**Comment by antifuchs** [comment]
Thanks!
