### ISSUE TITLE
support indenting attrset args according to RFC 166

### ISSUE THREAD

**Issue by Atemu** [nix-community/nix-ts-mode#27]
Trying to indent the args here does not work; it forces them onto column 0:

```
{
config,
pkgs,
lib,
...
}:
```

Perhaps the rule of "one further than the parent" could be generalised now that we have an official Nix style which lays out precise rules on that: https://github.com/NixOS/rfcs/pull/166

**Comment by gekoke** [comment]
I also observe this behavior after starting to use `nixfmt` with RFC-style.

**Comment by marsam** [comment]
I plan to work on this next week.
Would you mind renaming the issue to "Support [RFC 166](https://github.com/NixOS/rfcs/pull/166) indentation"?
